In [1]:
## 1. Create a 1D array of numbers from 0 to 9.

In [2]:
import numpy as np

In [5]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
## 2. Create a 3×3 numpy array of all True’s

In [8]:
bool_arr = np.ones((3,3), dtype=bool)
print(bool_arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
## 3. Given an array as input, print only odd numbers as output

In [5]:
arr=np.array(range(1,100))
arr_odd = arr[arr%2!=0]
print("odd number ", arr_odd)

odd number  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
## 4. Replace all odd numbers in arr with -2

In [20]:
arr=np.array(range(1,100))
arr_odd = (arr%2==1)
arr[arr_odd] = -2
print("replace odd number with '-2' :", arr)

replace odd number with '-2' : [-2  2 -2  4 -2  6 -2  8 -2 10 -2 12 -2 14 -2 16 -2 18 -2 20 -2 22 -2 24
 -2 26 -2 28 -2 30 -2 32 -2 34 -2 36 -2 38 -2 40 -2 42 -2 44 -2 46 -2 48
 -2 50 -2 52 -2 54 -2 56 -2 58 -2 60 -2 62 -2 64 -2 66 -2 68 -2 70 -2 72
 -2 74 -2 76 -2 78 -2 80 -2 82 -2 84 -2 86 -2 88 -2 90 -2 92 -2 94 -2 96
 -2 98 -2]


In [24]:
##Another Method:
    
arr[arr%2==1] = -2
print(arr)

[-2  2 -2  4 -2  6 -2  8 -2 10 -2 12 -2 14 -2 16 -2 18 -2 20 -2 22 -2 24
 -2 26 -2 28 -2 30 -2 32 -2 34 -2 36 -2 38 -2 40 -2 42 -2 44 -2 46 -2 48
 -2 50 -2 52 -2 54 -2 56 -2 58 -2 60 -2 62 -2 64 -2 66 -2 68 -2 70 -2 72
 -2 74 -2 76 -2 78 -2 80 -2 82 -2 84 -2 86 -2 88 -2 90 -2 92 -2 94 -2 96
 -2 98 -2]


In [25]:
## 5. How to reshape an array?

In [6]:
array = np.arange(10).reshape(2,5)
print(array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
# 6. Convert a 1D array to a 2D array with 2 rows

In [19]:
array_1D = np.arange(20)

print("1D Array : ",array_1D)

array_2D = np.reshape(array_1D,(10,2))
print("Convert 1D to 2D Array : ", array_2D)

1D Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Convert 1D to 2D Array :  [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [20]:
# 7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , 
# create  new array b from a such that b includes all odd numbers and 4 multiples. 

In [72]:
a = np.array([1,2,3,4,5,6,7,8,9])
print("Given array 'a' :", a)
b = a[((a%2) != 0) | ((a%4) == 0)]

print("All odd numbers and 4 multiples :", b)


Given array 'a' : [1 2 3 4 5 6 7 8 9]
All odd numbers and 4 multiples : [1 3 4 5 7 8 9]


In [70]:
# 8. Given array, check if there are any null values and print them out.

In [92]:
an_array = np.empty((3,3))
an_array[:] = np.NaN

print(an_array)


[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [93]:
# 9. How to replace all missing values with 0 in a numpy array?

In [107]:
x = np.array([1, 2,3,np.nan,4,5,np.nan,np.nan,6,7,8,9,np.nan,10,11]).reshape(3,5)
print("Originanl array :", x)
x[np.isnan(x) == 1] = 0
print("Replace missing values with 0 :" , x)

Originanl array : [[ 1.  2.  3. nan  4.]
 [ 5. nan nan  6.  7.]
 [ 8.  9. nan 10. 11.]]
Replace missing values with 0 : [[ 1.  2.  3.  0.  4.]
 [ 5.  0.  0.  6.  7.]
 [ 8.  9.  0. 10. 11.]]


In [108]:
# 10. How to find the count of each unique number in a NumPy array?

In [116]:
arr = np.array([1, 1, 2, 3, 4, 4, 1, 1, 5, 6, 7, 4, 5, 6, 9])

# Get unique values and count
(unique, counts) = np.unique(arr, return_counts=True)

frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 4]
 [2 1]
 [3 1]
 [4 3]
 [5 2]
 [6 2]
 [7 1]
 [9 1]]


In [117]:
# 11. How to convert a numeric to a categorical (text) array?

In [136]:
num_arr = np.arange(21).reshape(7,3)

print("Original array :",num_arr)

str_arr = num_arr.astype(str)

print("Covert to Categorical array :",str_arr)

Original array : [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
Covert to Categorical array : [['0' '1' '2']
 ['3' '4' '5']
 ['6' '7' '8']
 ['9' '10' '11']
 ['12' '13' '14']
 ['15' '16' '17']
 ['18' '19' '20']]


In [137]:
# 12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7.
# Exclude the elements which are divisible by both. 

In [168]:
a_arr = np.arange(99,299)

print("\n numbers between 99 and 299 : \n",a_arr)

arr_div = a_arr[(a_arr%5 == 0) | (a_arr%7 == 0)]

print("\n numbers either divisible by 5 or 7 : \n",arr_div)

arr_div_exclude = arr_div[(arr_div%5 == 0) & (arr_div%7 == 0)]

print("\n numbers both divisible by 5 and 7 : \n",arr_div_exclude)

arr_div = np.delete(arr_div,np.argwhere((arr_div%5 == 0) & (arr_div%7 == 0)))

print("\n exclude numbers both divisible by 5 and 7 : \n",arr_div)


 numbers between 99 and 299 : 
 [ 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298]

 numbers either divisible by 5 or 7 : 
 [100 105 110 112 115 119 120 125 126 130 133 135 140 145 147 150 154 155
 160 161 165 168 170 175 180 182 185 189

In [169]:
# 13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [176]:
init_arr = np.arange(50)

print("\n Original Array : \n", init_arr)

rev_arr = init_arr[::-1]

print("\n Reversal Array : \n",rev_arr)


 Original Array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]

 Reversal Array : 
 [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
